### ISSUE TITLE
Invalidating sessions based on time inactive instead of time created

### ISSUE THREAD

**Issue by vimalloc** [mbr/flask-kvsession#23]
I want to set this up so that each time a user loads a page, it keeps track of when that was, and if a timeout (PERMANENT_SESSION_LIFETIME probably) is greater then that, clear the session.

As it stands, it looks like the created timestamp is encoded in they key for this entry. Thus, to update the timestamp when the user accesses a page, it would need to get the data from that kv map, create a new entry with a new timestamp encoded in the key, delete the old key, and get the new cookie to the client. Yuck.

I was thinking that I would do something instead where there were two fields in the kv map.
- uniq_str
- uniq_str_accessed 

Where the first one has the session data and the second one mapped to a timestamp for the last time a page was accessed. Then I can just add a "update timestamp" call in app.before_requeset() to keep the timestamp up to date, and have clear_sessions() remove sessions accordingly.

What are your thoughts on this? Does this seem like a good way to go about it? Would you be interested in a patch that enables this as an option, or should I make this just for me?

**Comment by ln2khanal** [comment]
@vimalloc, I am suffering from the similar type of problem. I wonder why nobody has replied to your query yet. Permanent session life time & inactivity timeout need to work together which is not with flask_kvsession. Hope to hear any sort of solution from anyone else.

Thanks!

**Comment by mbr** [comment]
I've ran the example code and I can reproduce the problem. Debugging this shows me that occasionally sessions are "forgotten", i.e. I can get four requests in a row that will start off of the same dictionary of sessions, add theirs. E.g. if the new session IDs are [A, B, C, D] and before those four requests the sessions X and Y existed, I'd end up with [X, Y, A], [X, Y, B], [X, Y, C] and [X, Y, D].

This seems like a race condition in Flask (which may be indicating that I am using the Session API wrong). The issue here is that `DictStorage` is not thread-safe. The only thread_safe storages I would recommend are redis and possibly Postgres. The file-backed storage might work as well, but do not count on it. Do these problems disappear when using Redis?

**Comment by SvenFestersen** [comment]
@ln2khanal I'm with you on this. I recently started to use flask_kvsession as a drop-in replacement for the normal session interface. It turns out that this problem makes it less of a simple "drop-in" because the behaviour is different from the original, as `SESSION_REFRESH_EACH_REQUEST` is ignored.

@mbr As far as I understand, the reason for this is that the validity of the session is checked by comparing the session creation time that is encoded in the session key to the current time. Since the session id is usually never updated, this results in invalidation of the session after `creation_time + life_time` instead of `last_activity_time + life_time`.

Of course this can be circumvented by calling `session.regenerate()` on each request, but wouldn't it make more sense to store the expiration time in the backend and check session validity against that (if `SESSION_REFRESH_EACH_REQUEST` is set)?

If such a feature would have the chance to be accepted, I'm more than willing to implement it.
